### ISSUE TITLE
[BUG] Malformed image names cause segfault

### ISSUE THREAD

**Issue by Daemonslayer2048** [hauler-dev/hauler#372]
**Environmental Info:**
- Darwin JHanafin-T47QWQJFVY 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:48:52 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6020 arm64

**Hauler Version:**
```
GitVersion:    1.1.1-dev.1
GitCommit:     1b77295
GitTreeState:  clean
BuildDate:     2024-11-15T04:34:28Z
GoVersion:     go1.23.2 X:boringcrypto
Compiler:      gc
Platform:      darwin/arm6
```
and 
```
GitVersion:    1.1.0
GitCommit:     3406d54
GitTreeState:  clean
BuildDate:     2024-10-04T22:33:32Z
GoVersion:     go1.23.2 X:boringcrypto
Compiler:      gc
Platform:      linux/amd64
```

**Describe the Bug:**
I run into a segmentation violation when a malformed image name is used, an example is provided not only of the output but of the image name that caused the issue. While this was clearly an issue with the writer of the manifest (me), this stemmed from me creating a very large manifest and accidentally adding two image names together from a bad copy paste. To be clear this is operator failure, however manifests can become very large and a segfault makes it difficult to debug what the real error is. 

**Expected Behavior:**
Some error regarding the image name would be helpful. 

**Actual Behavior:**
```
2024-11-27 09:09:04 INF adding 'image' [rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3] to the store
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x1064a3a68]

goroutine 1 [running]:
hauler.dev/go/hauler/cmd/hauler/cli/store.storeImage({0x10d21c678, 0x1400078ac30}, 0x140007102a0, {{0x14006c9c1c0, 0x34}, {0x0, 0x0}, {0x0, 0x0}}, {0x16b377365, ...}, ...)
        /home/runner/work/hauler/hauler/cmd/hauler/cli/store/add.go:82 +0x1d8
hauler.dev/go/hauler/cmd/hauler/cli/store.processContent({0x10d21c678, 0x1400078ac30}, 0x1400001d670, 0x140003b7580, 0x140007102a0, 0x140008008a0)
        /home/runner/work/hauler/hauler/cmd/hauler/cli/store/sync.go:191 +0xeb8
hauler.dev/go/hauler/cmd/hauler/cli/store.SyncCmd({0x10d21c678, 0x1400078ac30}, 0x140003b7580, 0x140007102a0, 0x140008008a0)
        /home/runner/work/hauler/hauler/cmd/hauler/cli/store/sync.go:74 +0x474
hauler.dev/go/hauler/cmd/hauler/cli.addStoreSync.func1(0x14000520f08?, {0x1064c7f01?, 0x4?, 0x1064c7f05?})
        /home/runner/work/hauler/hauler/cmd/hauler/cli/store.go:78 +0x78
github.com/spf13/cobra.(*Command).execute(0x14000520f08, {0x14000596ae0, 0x6, 0x6})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000520308)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(0x10d21c678?, {0x10d21c678?, 0x1400078ac30?})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034 +0x48
main.main()
        /home/runner/work/hauler/hauler/cmd/hauler/main.go:24 +0xc8
make: *** [build_foss_packages] Error 2
```

**Steps to Reproduce:**
Use the manifest below: 
```yaml
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-foss-images
spec:
  images:
    - name: rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3
```

**Comment by zackbradys** [comment]
hey @Daemonslayer2048, thanks for the overview and suggestion on improved logging... I agree and we will look at improving this in a upcoming release so users are more informed due to why they are getting the error...

**Comment by zackbradys** [comment]
hey @Daemonslayer2048, it looks like I wasn't able to reproduce this error, but it is working in `v1.1.1`. Could it give it another try and if it still happening then please reopen this issue!

```bash
zackbradys@Zacks-MacBook-Pro hauler % hauler version
 __    __       ___       __    __   __       _______ .______
|  |  |  |     /   \     |  |  |  | |  |     |   ____||   _  \
|  |__|  |    /  ^  \    |  |  |  | |  |     |  |__   |  |_)  |
|   __   |   /  /_\  \   |  |  |  | |  |     |   __|  |      /
|  |  |  |  /  _____  \  |  `--'  | |  `----.|  |____ |  |\  \----.
|__|  |__| /__/     \__\  \______/  |_______||_______|| _| `._____|
hauler: Airgap Swiss Army Knife

GitVersion:    1.1.1
GitCommit:     090f4dc
GitTreeState:  clean
BuildDate:     2024-12-09T13:36:45Z
GoVersion:     go1.23.4 X:boringcrypto
Compiler:      gc
Platform:      darwin/arm64
zackbradys@Zacks-MacBook-Pro hauler %
zackbradys@Zacks-MacBook-Pro hauler % 
zackbradys@Zacks-MacBook-Pro hauler % cat manifest.yaml 
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-foss-images
spec:
  images:
    - name: rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3
zackbradys@Zacks-MacBook-Pro hauler %
zackbradys@Zacks-MacBook-Pro hauler %
zackbradys@Zacks-MacBook-Pro hauler % hauler store sync -f manifest.yaml 
2024-12-13 23:26:41 INF syncing [content.hauler.cattle.io/v1alpha1, Kind=Images] to store
2024-12-13 23:26:41 INF adding 'image' [rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3] to the store
2024-12-13 23:26:41 ERR unable to parse 'image' [rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3]: could not parse reference: rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3
Error: could not parse reference: rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3
Usage:
  hauler store sync [flags]

Flags:
  -f, --files strings             Location of content manifests (files)... i.e. --files ./rke2-files.yaml
  -h, --help                      help for sync
  -k, --key string                (Optional) Location of public key to use for signature verification
  -p, --platform string           (Optional) Specify the platform of the image... i.e linux/amd64 (defaults to all)
  -c, --product-registry string   (Optional) Specify the product registry. Defaults to RGS Carbide Registry (rgcrprod.azurecr.us)
      --products strings          (Optional) Specify the product name to fetch collections from the product registry i.e. rancher=v2.8.5,rke2=v1.28.11+rke2r1
  -g, --registry string           (Optional) Specify the registry of the image for images that do not alredy define one

Global Flags:
  -d, --haulerdir string   Set the location of the hauler directory (default $HOME/.hauler)
      --ignore-errors      Ignore/Bypass errors (i.e. warn on error) (defaults false)
  -l, --log-level string   Set the logging level (i.e. info, debug, warn) (default "info")
  -r, --retries int        Set the number of retries for operations (default 3)
  -s, --store string       Set the directory to use for the content store

2024-12-13 23:26:41 ERR could not parse reference: rancher/rancher:v2.8.3rancher/rancher-webhook:v0.4.3
```
